### ISSUE TITLE
New build not working

### ISSUE THREAD

**Issue by ghost** [bloomberg/chef-bcpc#527]
Building on my laptop it appears to get dependency issues on keystone, python-keystone, oslo. I have attempted to install twice and the error is consistent:

[2015-03-30T15:40:36-04:00] INFO: Processing ruby_block[initialize-keystone-config] action run (bcpc::keystone line 23)
++++++++++++ Creating new item with key "mysql-keystone-user"
++++++++++++ Creating new item with key "mysql-keystone-password"
++++++++++++ Creating new item with key "keystone-admin-token"
++++++++++++ Creating new item with key "keystone-admin-user"
++++++++++++ Creating new item with key "keystone-admin-password"
------------ Fetching value for key "keystone-pki-certificate"
++++++++++++ Creating new item with key "keystone-pki-private-key"
++++++++++++ Creating new item with key "keystone-pki-certificate"
[2015-03-30T15:40:37-04:00] INFO: ruby_block[initialize-keystone-config] called
[2015-03-30T15:40:37-04:00] INFO: Processing package[keystone] action upgrade (bcpc::keystone line 42)

================================================================================
Error executing action `upgrade` on resource 'package[keystone]'
================================================================================

Mixlib::ShellOut::ShellCommandFailed
------------------------------------
Expected process to exit with [0], but received '100'
---- Begin output of apt-get -q -y install keystone=1:2014.1.4-0ubuntu1~cloud0 ----
STDOUT: Reading package lists...
Building dependency tree...
Reading state information...
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 keystone : Depends: python-keystone (= 1:2014.1.4-0ubuntu1~cloud0) but it is not going to be installed
STDERR: E: Unable to correct problems, you have held broken packages.
---- End output of apt-get -q -y install keystone=1:2014.1.4-0ubuntu1~cloud0 ----
Ran apt-get -q -y install keystone=1:2014.1.4-0ubuntu1~cloud0 returned 100

Resource Declaration:
---------------------
# In /var/chef/cache/cookbooks/bcpc/recipes/keystone.rb

 42:     package pkg do
 43:         action :upgrade
 44:     end
 45: end

Compiled Resource:
------------------
# Declared in /var/chef/cache/cookbooks/bcpc/recipes/keystone.rb:42:in `block in from_file'

package("keystone") do
  action [:upgrade]
  retries 0
  retry_delay 2
  guard_interpreter :default
  package_name "keystone"
  version "1:2014.1.4-0ubuntu1~cloud0"
  timeout 900
  cookbook_name "bcpc"
  recipe_name "keystone"
end

[2015-03-30T15:40:37-04:00] INFO: Running queued delayed notifications before re-raising exception
[2015-03-30T15:40:37-04:00] INFO: template[/etc/ntp.conf] sending restart action to service[ntp] (delayed)
[2015-03-30T15:40:37-04:00] INFO: Processing service[ntp] action restart (ntp::default line 108)
[2015-03-30T15:40:39-04:00] INFO: service[ntp] restarted
[2015-03-30T15:40:39-04:00] INFO: bash[apache-enable-ssl] sending restart action to service[apache2] (delayed)
[2015-03-30T15:40:39-04:00] INFO: Processing service[apache2] action restart (bcpc::apache2 line 64)
[2015-03-30T15:40:42-04:00] INFO: service[apache2] restarted
[2015-03-30T15:40:42-04:00] INFO: cookbook_file[/usr/local/bin/routemon.pl] sending restart action to service[routemon] (delayed)
[2015-03-30T15:40:42-04:00] INFO: Processing service[routemon] action restart (bcpc::networking-route-test line 42)
[2015-03-30T15:40:42-04:00] INFO: service[routemon] restarted
[2015-03-30T15:40:42-04:00] INFO: template[/etc/init/routemon.conf] sending start action to service[routemon] (delayed)
[2015-03-30T15:40:42-04:00] INFO: Processing service[routemon] action start (bcpc::networking-route-test line 42)
[2015-03-30T15:40:42-04:00] INFO: template[/etc/mysql/my.cnf] sending restart action to service[mysql] (delayed)
[2015-03-30T15:40:42-04:00] INFO: Processing service[mysql] action restart (bcpc::mysql-common line 40)
[2015-03-30T15:40:49-04:00] INFO: service[mysql] restarted
[2015-03-30T15:40:49-04:00] INFO: execute[enable-rabbitmq-web-mgmt] sending restart action to service[rabbitmq-server] (delayed)
[2015-03-30T15:40:49-04:00] INFO: Processing service[rabbitmq-server] action restart (bcpc::rabbitmq line 88)
[2015-03-30T15:40:54-04:00] INFO: service[rabbitmq-server] restarted
[2015-03-30T15:40:54-04:00] INFO: template[/etc/haproxy/haproxy.pem] sending restart action to service[haproxy] (delayed)
[2015-03-30T15:40:54-04:00] INFO: Processing service[haproxy] action restart (bcpc::haproxy-common line 57)
[2015-03-30T15:40:59-04:00] INFO: service[haproxy] restarted
[2015-03-30T15:40:59-04:00] ERROR: Running exception handlers
[2015-03-30T15:40:59-04:00] ERROR: Exception handlers complete
[2015-03-30T15:40:59-04:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
[2015-03-30T15:40:59-04:00] ERROR: package[keystone] (bcpc::keystone line 42) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '100'
---- Begin output of apt-get -q -y install keystone=1:2014.1.4-0ubuntu1~cloud0 ----
STDOUT: Reading package lists...
Building dependency tree...
Reading state information...
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 keystone : Depends: python-keystone (= 1:2014.1.4-0ubuntu1~cloud0) but it is not going to be installed
STDERR: E: Unable to correct problems, you have held broken packages.
---- End output of apt-get -q -y install keystone=1:2014.1.4-0ubuntu1~cloud0 ----
Ran apt-get -q -y install keystone=1:2014.1.4-0ubuntu1~cloud0 returned 100
[2015-03-30T15:40:59-04:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
Connection to 127.0.0.1 closed.

real	30m44.367s
user	0m23.879s
sys	0m8.189s

**Comment by mihalis68** [comment]
I'll investigate

**Comment by kamidzi** [comment]
confirmed.

**Comment by kamidzi** [comment]
```
$ apt-cache depends python-oslo.serialization python-keystone  | tee /dev/tty | tail -1 | tr -d '<>' | xargs apt-cache policy
...
  Suggests: python-memcache
<python-oslo.serialization>
apt-cache policy python-oslo.serialization
python-oslo.serialization:
  Installed: (none)
  Candidate: (none)
  Version table:
```

Sums up the situation

**Comment by kamidzi** [comment]
@caiush and I spoke offline. The consensus was to try switching the repo targets from "proposed" to "updates". See https://github.com/bloomberg/chef-bcpc/blob/master/cookbooks/bcpc/attributes/default.rb#L12

**Comment by kkoh61** [comment]
Other than hitting a fatal failure attempting to patch #493 , I am able to build cleanly. There is a number of packages, not limited to, percona, qemu, openstack, ceph, etc. Curious if anyone else is in similar situation.

**Comment by mihalis68** [comment]
Switching to 'updates' I was able to do a clean build all the way to three nodes running and hitting Horizon. This is on the non-vagrant path. Sorry for the delay between saying I'd check and actually getting it done!

**Comment by kkoh61** [comment]
Typed previous comment in a haste. Summarily, while various packages have been updated, I am able to build cleanly (other than above-mentioned patch failure) with "proposed". The installed python-keystone version is now 1:2014.1.4-0ubuntu2~cloud0 (released Apr 8). We probably should use "updates" and package pinning, but it looks like we have escaped this issue for now unless this can be reproduced.

**Comment by kkoh61** [comment]
Created #536 to address the nova patch error.

**Comment by kkoh61** [comment]
Build runs clean after merging #536. Version pinning (#523) and switching to "updates" repository (#539) should resolve the issue of pulling untested packages.

**Comment by kamidzi** [comment]
Excellent. When I had attempted using updates after my last comment, I was still experiencing failures; I agree that a persistent issue is the lack of strict dependency specification...
